---
- name: ETCD-CLUSTER
  hosts: etcd
  become: true
  tasks:
    - name: 'Install unzip/tar'
      dnf:
        name: 
          - unzip
          - tar
    - name: "Pull etcd"
      get_url:
        url: '{{google_url}}/{{etcd_version}}/etcd-{{etcd_version}}-linux-amd64.tar.gz'
        dest: "{{ ansible_env.HOME }}"
        checksum: md5:8107d61ea56d32f4c90581bb3a22e021
    - name: 'Pull cfssl'
      get_url:
        url: '{{cfssl_download_url}}/v{{cfssl_version}}/cfssl-bundle_{{cfssl_version}}_linux_amd64'
        dest: '/opt'
        
        checksum: md5:8a52204bc7d319bc06cce810133153f6        
    - name: "Unpack etcd"   
      unarchive: 
        src: '{{ ansible_env.HOME }}/etcd-{{etcd_version}}-linux-amd64.tar.gz'
        dest: '/opt'
        remote_src: yes
    - name: etcd dir symlink
      ansible.builtin.file:
        src: /opt/etcd-{{etcd_version}}-linux-amd64
        dest: /opt/etcd
        state: link           
    - name: etcd dir symlink
      ansible.builtin.file:
        src: /opt/etcd/etcd
        dest: /usr/bin/etcd
        state: link                 
    - name: cfssl exec symlink
      ansible.builtin.file:
        src: /opt/cfssl-bundle_{{cfssl_version}}_linux_amd64
        dest: /usr/bin/cfssl
        state: link            